language: java
jdk: oraclejdk8
cache:
  directories:
    - node_modules
    - $HOME/.m2
script: mvn verify
services:
   - mysql
before_install:
  - mysql -e 'CREATE DATABASE usersDB;'
after_success:
  - surge --project ./target/site --domain mikkeldjurhuus.surge.sh
after_failure:
  #Remove documentation for a failing project
  - surge teardown mikkeldjurhuus.surge.sh

